# Generated by Django 5.1.7 on 2025-03-20 14:54

from django.db import migrations

def insert_holidays(apps ,schema_editor):
    TimeSlot = apps.get_model('timeschedulingweb','TimeSlot')
    TimeSlot(start_time='2025-01-01T00:00:00',
            end_time='2025-05-01T23:59:59',
            description='labour day').save()
    TimeSlot(start_time='2025-07-15T00:00:00',
            end_time='2025-07-15T23:59:59',
            description='Independence day').save()
    TimeSlot(start_time='2025-03-30T00:00:00',
            end_time='2025-03-30T23:59:59',
            description='Gudi Padwa day').save()

class Migration(migrations.Migration):

    dependencies = [
        ('timeschedulingweb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_holidays)
    ]
