# Generated by Django 5.1.7 on 2025-03-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0003_currencyhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='exchange_data',
            new_name='exchange_date',
        ),
    ]
